name: Build docs

permissions:
  pull-requests: write
  issues: write
  repository-projects: write
  contents: write

on:
  pull_request:
  push:
    branches: [main]

jobs:
  docs:
    name: "Build docs"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"
          cache-dependency-path: |
            ./requirements.txt
      - run: pip3 install -r requirements.txt
      - run: make html
        name: "Build sphinx documentation"
      - name: Deploy docs
        uses: peaceiris/actions-gh-pages@v4
        if: success() && github.ref == 'refs/heads/main' # only deploy main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/html
